### ISSUE TITLE
Quirky vertex editing after discarding working copy changes

### ISSUE THREAD

**Issue by rcoup** [koordinates/kart-qgis-plugin#38]
1. add a point layer to the map
2. select a feature
3. move it using the **vertex tool** (not Move Feature). Remember where you moved it to.
4. save the edits
5. Toggle editing off
6. Kart... Discard working tree changes. Point moves back to where it originally was, as expected
7. Toggle editing on again
8. Try and select the vertex you edited in (2) by right clicking on it's current/visible location - doesn't work
9. Try and select the vertex  you edited in (2) by right clicking on it's discarded location - works. Then it jumps back to where it should be.
10. Select the vertex  you edited in (2) by dragging a box on it's current location - highlights the discarded location

Something weird going on... might be a vertex tool bug? Or some context not getting cleared properly?

https://user-images.githubusercontent.com/59874/143026647-a7c876f2-a766-4c69-bb57-6feae8887bb6.mp4

**Comment by olsen232** [comment]
FYI I've run into situations like this without using the Kart QGIS plugin - just using Kart directly. Hitting every possible "refresh" button on QGIS may not cause QGIS to actually properly reload everything, although it sometimes gets halfway there eg the layer might visibly refresh, but end up out of sync with the clickable and editable points of that layer. When I absolutely need everything to work first try (eg for a demo), I do harsher resets - removing and re-adding the appropriate layer, or even, restarting QGIS.
Anyway all this to say, the bug may be deep in QGIS rather than anything Kart related.
