### ISSUE TITLE
Option to display spatial filter extents on the map

### ISSUE THREAD

**Issue by rcoup** [koordinates/kart-qgis-plugin#45]
If a user has spatial filter(s) set, would be good to be able to (optionally) see the borders of the filters on the map.

IMO ideally they wouldn't appear as layers, but maybe more like a decoration (ie: layout extents, grids, etc)? Maybe @hamishcampbell has other ideas?

**Comment by volaya** [comment]
The common practice in that case is not to use a layer, but a rubberband (using the QgsRubberBand class), which will be painted on the map canvas, and works as a decoration.

**Comment by hamishcampbell** [comment]
That would be ideal.

**Comment by volaya** [comment]
This is already implemented. Now the layers from a repo with a spatial filter will have the filter bounding box drawn in the map canvas

![image](https://user-images.githubusercontent.com/2101651/144989272-d8cf13eb-4498-40b1-8298-e0f9c7f6d373.png)

In the repo properties, you can disable that or change the color used to paint the bounding box

![image](https://user-images.githubusercontent.com/2101651/144989492-88bf2a12-50d5-4c0f-ac1e-500af11e4aca.png)

Let me know what you think

**Comment by volaya** [comment]
Rubber bands are not reprojected on-the fly when the user changes the CRS of the map canvas, but I added the code to reproject them when that happens, so they should stay in place even if the canvas changes its properties.

When the layer is removed, the bounding box is deleted.

**Comment by rcoup** [comment]
Looks good — I'd suggest making the lineweight thinner/less dense, and maybe add a label with the repo title, since if you're working with layers from multiple repos you could have multiple active filters?

eg (but more subtle):
![CleanShot 2021-12-07 at 12 11 02](https://user-images.githubusercontent.com/59874/145026929-fafbd610-83cc-4317-af58-b43a21aeeb4d.png)

What do you think @brentneave?

**Comment by brentneave** [comment]
Yes that makes sense @rcoup. I suppose the main thing, if we change the styling of the spatial filter boundary, might be making sure it remains visually distinct from any layer geometry it might enclose or overlap.

**Comment by edcorkery** [comment]
@timdenee export step handling is relevant

**Comment by volaya** [comment]
Adding text in the canvas is available from QGIS 3.22, with annotation layers. Instead of using that, I have used the classic canvas annotations, but removing the frame and the background, so they look like normal text labels. Later we can move to annotation layers, which will give us more control over the rendering and the styling of the text.

Using annotations makes things a bit more complex, since those are saved in the project (unlike rubber bands), so it is a bit tricky to handle kart  layers in a saved QGIS project. Annotations object names are not saved, so there is no way to later identify an annotation as belonging to a kart repo filter (to hide it or show it according to what the user selects). What I have done is to prefix the label name with "kart:", so we can easily identify it when a project is opened and have full control over its rendering.

I think the code is working fine now in all these cases, but please test and let me know what you think.

Also, now it will not add multiple rubberbands if there are multiple layers from the same repo. It will just render one bounding box per repo.

**Comment by rcoup** [comment]
Looks great :-)
