### ISSUE TITLE
Incorrect Kart version parsing/compatibility

### ISSUE THREAD

**Issue by rcoup** [koordinates/kart-qgis-plugin#59]
**Describe the bug**

Kart versions like 0.11.0rc4 fail in QGIS.

**To Reproduce**

1. Install Kart [v0.11.0rc4](https://github.com/koordinates/kart/actions/runs/1742916624)
2. in QGIS, go to _Plugins...Kart...Repositories_
3. Get message "The installed Kart version (0.11.04) is different from the version supported by the plugin (0.10.8)"

**Expected behavior**

Kart [follows SemVer with PEP-440 version numbering](https://github.com/koordinates/kart/blob/master/HOWTO-RELEASE.md#user-content-prerequisites). Kart quite often has [alpha, beta & rc releases](https://github.com/koordinates/kart/tags?after=v0.10.4rc1), and we use eg: `0.10.9.dev0` for local developer builds.

I guess we need to parse & compare versions in the same way PEP-440 does/describes?

**Version info**
  ```
Kart Plugin version
dev-7992f473acf09375b54d007bebb04b8f6ac86a78
QGIS version
3.20.3-Odense
Operating system
macOS 11.6.3 x86_64 i386 64bit
Kart version
Kart v0.11.0rc4, Copyright (c) Kart Contributors
» GDAL v3.4.1; PROJ v7.2.1
» PyGit2 v1.7.0; Libgit2 v1.3.0; Git v2.34.0
» SQLAlchemy v1.4.29; pysqlite3 v2.6.0/v3.37.2; SpatiaLite v5.0.1; Libpq v14.0.1
» SpatialIndex v1.9.3
```

**Comment by volaya** [comment]
We are already parsing versions like that (including support for RC versions). The warning message is shown because the current criteria that we are using for accepting the installed version is that it must have the same major and minor version numbers as the one supported by the plugin. Should we change that and accept changes in the minor version? AFAIK, there have some changes in the commands syntax between minor versions that would cause the plugin to fail

**Comment by rcoup** [comment]
We should work off the principle that newer minor versions (eg: 0.10 → 0.11 → 0.12; 1.0 → 1.1 → 1.2) are compatible, and the Kart version the QGIS plugin requires is a minimum.

I guess at 1.0 we might need to revisit/adjust, but that's a future problem
